### ISSUE TITLE
consider using gRPC

### ISSUE THREAD

**Issue by berndhopp** [DP-3T/dp3t-sdk-backend#39]
protobuf allows for services to be defined like this:

service DP3TService {
    rpc registerExposition(Exposee) returns (Void);
    rpc getExpositionsSince(int64) return (stream Exposee);
}

gRPC is an implementation of these services which also allows for client and server-side authentication and provides a great java-API, it is the de-facto standard when it comes to protobuf-rpc. Please consider switching over to gRPC instad of the REST/protobuf-hybrid that is in place now.

**Comment by ubamrein** [comment]
Hi there! thanks for the suggestion. 
Currently we have no plans on switching to gRPC. 

I try to give some arguments of why not:

1) We still want to support JSON. 
2) We are using SpringBoot and hope to provide a setting, where other Content-Types can be easily integrated (since e.g. JSON support is much better than protobuf, or someone wants to use xmlsig, or even msgpack or CBOR or whatever)
3) We don't think that we would have any advantages of using gRPC other than breaking support with various clients. 
4) Since it is crucial that many people have a look at it and comment on the design, I am not sure if gRPC has enough coverage compared to REST. So in our opinion people are more likely to follow the REST Api Code.
