### ISSUE TITLE
Clarification on "batchReleaseTime"

### ISSUE THREAD

**Issue by josemmo** [DP-3T/dp3t-sdk-backend#49]
Could you provide the use case for "batchReleaseTime"? I'm unable to find any documentation related to that.

I guess it has something to do with the time when an exposee key was uploaded to the server, but I'm having trouble understanding the difference between calling `/exposed/{batchReleaseTime}` and `/exposed/{YYYY-MM-DD}`.

**Comment by martinalig** [comment]
The API got some refactoring last week and the README is not yet fully updatet, we will try to improve this during the next days.
Currently, the API is: /exposed/{batchReleaseTime} whereas batchReleaseTime is a Unix Timestamp in milliseconds. (The endpoint with YYYY-MM-DD is not used anymore)
And yes, the batchReleaseTime contains keys, which have been uploaded in the last N hours, depending on the configuration of the system. Default this is two hours.

**Comment by josemmo** [comment]
Looking at the source code, `batchReleaseTime` seems to be the latest time allowed in a exposed list request:
https://github.com/DP-3T/dp3t-sdk-backend/blob/c4638064e54fc54185f7d213a132ced8d29c29f0/dpppt-backend-sdk/dpppt-backend-sdk-data/src/main/java/org/dpppt/backend/sdk/data/JDBCDPPPTDataServiceImpl.java#L112-L119

So, if I undestood correctly, a client will send a request for `/exposed/{now}` and keep sending requests with lower timestamps (`/exposed/{now-2h}`, `/exposed/{now-4h}`, etc.) to get a full day of uploaded exposed keys, right?

**Comment by ubamrein** [comment]
Yes almost. The idea is to split the day into buckets (default 2h) and you can get the complete day as you said.
Be careful since the timestamp __must__ match a bucket (e.g. timestamp % bucket_length == 0).
So your first request should be adjusted to something like `/exposed/{Math.floor(now/batch_length)*batch_length}`

**Comment by josemmo** [comment]
Thanks for the explanation!

Also, couldn't "batchReleaseTime" be expressed in seconds (instead of milliseconds) or is there a reason for that?

**Comment by ubamrein** [comment]
We use internally timestamps with milliseconds as this is the standard in Java. Another reason is to force everyone to use longs. As such we wanted to be consistent across objects and API calls. In theory you could also also use seconds (but integer overflow will come soon, so you need longs anyways).

**Comment by josemmo** [comment]
Given milliseconds are never used and the database stores the timestamp without them, I believe "batchReleaseTime" should be a UNIX timestamp (without milliseconds).

I get that you want people to use `long`s to avoid date overflows in 2038, but I don't think this is the right way of doing it (some developers will write bad code regardless, e.g. using `string`s). Also, you can always store seconds in a `long`:

```java
long time = System.currentTimeMillis() / 1000L;
```

**Comment by ubamrein** [comment]
Fair point, but it is not really an argument to use seconds is it? To me it is not clear why to use seconds over milliseconds, if it is clearly specified (and yes we need to document it more carefully). 

We'd rather not change that now since it would need to be changed on all clients as well.

Can you think of any major issue related to using milliseconds? If not I would stop the discussion here (and close the issue as soon as we added documentation)

**Comment by josemmo** [comment]
My only argument for using seconds is that the information being represented does not use milliseconds. But if it's already too late for changing it, then it makes sense to leave as it is.

Well, at least I tried. Sorry if that bothered you as that was not my intention.

**Comment by ubamrein** [comment]
No worries, sorry didn't mean to sound harsh. 

But then I guess we leave it at milliseconds!

Thanks for the inputs!
